import React, { useState } from 'react';
import { SparklesIcon } from './Icons';
import { Stock, AIAnalysisResult } from '../types';
import { analyzeMarket } from '../services/geminiService';

interface Props {
  stocks: Stock[];
}

const AIInsights: React.FC<Props> = ({ stocks }) => {
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<AIAnalysisResult | null>(null);

  const handleAnalyze = async () => {
    setLoading(true);
    const result = await analyzeMarket(stocks);
    setAnalysis(result);
    setLoading(false);
  };

  return (
    <div className="bg-gradient-to-br from-indigo-900/30 to-trade-card rounded-lg border border-indigo-500/30 p-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-indigo-400 text-xs font-bold uppercase tracking-wider flex items-center gap-2">
          <SparklesIcon className="w-4 h-4" />
          AI Market Pulse
        </h3>
        <button
          onClick={handleAnalyze}
          disabled={loading}
          className="text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1.5 rounded-md transition-colors disabled:opacity-50 flex items-center gap-1"
        >
          {loading ? 'Analyzing...' : 'Refresh Insight'}
        </button>
      </div>

      {!analysis && !loading && (
        <div className="text-sm text-trade-muted text-center py-6">
          Click refresh to get real-time market sentiment analysis powered by Gemini.
        </div>
      )}

      {loading && (
        <div className="space-y-2 animate-pulse">
          <div className="h-4 bg-slate-700 rounded w-3/4"></div>
          <div className="h-4 bg-slate-700 rounded w-full"></div>
          <div className="h-4 bg-slate-700 rounded w-5/6"></div>
        </div>
      )}

      {analysis && !loading && (
        <div className="space-y-3 animate-fade-in">
          <div className="flex items-center gap-2">
            <span className="text-xs text-trade-muted">Sentiment:</span>
            <span className={`text-xs font-bold px-2 py-0.5 rounded ${
              analysis.sentiment === 'BULLISH' ? 'bg-green-500/20 text-green-400' :
              analysis.sentiment === 'BEARISH' ? 'bg-red-500/20 text-red-400' :
              'bg-yellow-500/20 text-yellow-400'
            }`}>
              {analysis.sentiment}
            </span>
          </div>
          
          <p className="text-sm text-trade-text leading-relaxed">
            {analysis.summary}
          </p>
          
          <div className="space-y-1">
            {analysis.keyPoints.map((point, idx) => (
              <div key={idx} className="flex gap-2 text-xs text-trade-muted">
                <span className="text-indigo-400">•</span>
                <span>{point}</span>
              </div>
            ))}
          </div>
          
          <div className="mt-2 text-[10px] text-slate-500 text-right">
            Generated by Gemini 2.5 Flash
          </div>
        </div>
      )}
    </div>
  );
};

export default AIInsights;
